version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-cli
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby
    versions:
    - 2.32.11
    - 2.32.9
  - dependency-name: gatsby-plugin-robots-txt
    versions:
    - 1.5.5
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
  - dependency-name: react
    versions:
    - 17.0.1
